/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicgame;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hieu
 */
public class MainFrame2 extends javax.swing.JFrame implements KeyListener, Runnable {

    /**
     * Creates new form MainFrame2
     */
    int x;
    int y;
    int rx, ry;
    int sx, sy;
    int dx, dy;
    
    public MainFrame2() {
        x = 100;
        y = 100;
        rx = 200;
        ry = 200;
        sx = 200;
        sy = 100;
        dx = 5;
        dy = 5;
        initComponents();
        addKeyListener(this);
        
        Thread th = new Thread(this);
        th.start();
    }
    
    @Override
    public void paint(Graphics g) {
//        super.paint(g); //To change body of generated methods, choose Tools | Templates.
//        // chon mau sac
//        g.setColor(Color.PINK);
//        g.drawRect(100, 100, 200, 50);
//        g.setColor(Color.BLUE);
//        g.fillRect(10, 20, 300, 75);
//        g.setColor(Color.CYAN);
//        g.fillOval(200, 200, 25, 50);
        g.setColor(Color.GRAY);
        g.fillRect(0, 0, 500, 500);
        g.setColor(Color.PINK);
        g.fillOval(x, y, 30, 30);
        
        g.setColor(Color.BLACK);
        g.fillRect(rx, ry, 20, 20);
        g.setColor(Color.ORANGE);
        g.fillRect(sx, sy, 25, 25);
        g.drawRect(100, 100, 125, 225);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame2().setVisible(true);
            }
        });
    }
    
    @Override
    public void keyTyped(KeyEvent e) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void keyPressed(KeyEvent e) {
        System.out.println("CODE cua phim ban vua ban la: " + e.getKeyCode());
        switch (e.getKeyCode()) {
            case KeyEvent.VK_UP:
                y = y - 10;
                break;
            case KeyEvent.VK_DOWN:
                y = y + 10;
                break;
            case KeyEvent.VK_RIGHT:
                x = x + 10;
                break;
            case KeyEvent.VK_LEFT:
                x = x - 10;
                break;
        }
    }
    
    @Override
    public void keyReleased(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void run() {
        while (true) {
            rx += (int) (Math.random() * 10) - 5;
            ry += (int) (Math.random() * 10) - 5;
            rx += 500;
            ry += 500;
            rx %= 500;
            ry %= 500;

            // bounce 
            sx += dx;
            sy += dy;
            if (sx > 500) {
                dx = -5;
            }
            if (sy > 500) {
                dy = -5;
            }
            if (sx < 0) {
                dx = 5;
            }
            if (sy < 0) {
                dy = 5;
            }
            repaint();
            try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainFrame2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
